In [ ]:
import pandas as pd
import numpy as np  
import tpqoa as tpqoa
import matplotlib.pyplot as plt

In [2]:
api = tpqoa.tpqoa("D:\\Dissertation Mohit\\Test Environment\\oanda.cfg")

In [3]:
mid = api.get_history(instrument="EUR_USD", start="2026-01-01", end="2026-02-28", price="M", granularity="M15")
mid

                           o        h        l        c  volume  complete
time
2026-01-01 22:00:00  1.17498  1.17505  1.17490  1.17498      49      True
2026-01-01 22:15:00  1.17497  1.17504  1.17490  1.17495      92      True
2026-01-01 22:30:00  1.17494  1.17496  1.17488  1.17490      98      True
2026-01-01 22:45:00  1.17490  1.17494  1.17474  1.17488     255      True
2026-01-01 23:00:00  1.17487  1.17492  1.17458  1.17466     371      True
...                      ...      ...      ...      ...     ...       ...
2026-02-27 20:45:00  1.18244  1.18254  1.18151  1.18162    1464      True
2026-02-27 21:00:00  1.18160  1.18161  1.18124  1.18142     930      True
2026-02-27 21:15:00  1.18140  1.18185  1.18133  1.18152     472      True
2026-02-27 21:30:00  1.18152  1.18177  1.18112  1.18117     364      True
2026-02-27 21:45:00  1.18116  1.18183  1.18116  1.18172    1400      True

[3936 rows x 6 columns]

In [4]:
mid.drop(columns=['o','l','h','volume','complete'], inplace=True)
mid.rename(columns={'c':'price'}, inplace=True)
mid

                       price
time
2026-01-01 22:00:00  1.17498
2026-01-01 22:15:00  1.17495
2026-01-01 22:30:00  1.17490
2026-01-01 22:45:00  1.17488
2026-01-01 23:00:00  1.17466
...                      ...
2026-02-27 20:45:00  1.18162
2026-02-27 21:00:00  1.18142
2026-02-27 21:15:00  1.18152
2026-02-27 21:30:00  1.18117
2026-02-27 21:45:00  1.18172

[3936 rows x 1 columns]

In [5]:
mid.to_csv("D:\\Dissertation Mohit\\Test Environment\\Data\\raw\\EURUSD_2026_01_01_to_2026_02_28.csv")

In [6]:
test = api.get_history(instrument="EUR_USD", start="2026-03-01", end="2026-03-07", price="M", granularity="M15")
test

                           o        h        l        c  volume  complete
time
2026-03-01 22:00:00  1.17685  1.17705  1.17652  1.17652     289      True
2026-03-01 22:15:00  1.17654  1.17658  1.17584  1.17629     508      True
2026-03-01 22:30:00  1.17630  1.17736  1.17630  1.17730     593      True
2026-03-01 22:45:00  1.17732  1.17796  1.17732  1.17773     438      True
2026-03-01 23:00:00  1.17770  1.17878  1.17661  1.17778    1940      True
...                      ...      ...      ...      ...     ...       ...
2026-03-06 20:45:00  1.16029  1.16099  1.16024  1.16060    1816      True
2026-03-06 21:00:00  1.16060  1.16172  1.16052  1.16169    1716      True
2026-03-06 21:15:00  1.16168  1.16182  1.16148  1.16161    1462      True
2026-03-06 21:30:00  1.16162  1.16162  1.16112  1.16112     857      True
2026-03-06 21:45:00  1.16110  1.16187  1.16072  1.16168    1630      True

[480 rows x 6 columns]

In [7]:
test.drop(columns=['o','l','h','volume','complete'], inplace=True)
test.rename(columns={'c':'price'}, inplace=True)
test.to_csv("D:\\Dissertation Mohit\\Test Environment\\Data\\test\\EURUSD_2026_03_01_to_2026_03_07.csv")